sonar.projectKey=codeurjc-students_2025-GoEventsNow
sonar.organization=codeurjc-students

sonar.sources=backend/src/main,frontend/src/app,frontend/src/assets,frontend/src/styles.css
sonar.tests=backend/src/test,frontend/src/app

sonar.test.inclusions=**/*.spec.ts

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/**/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.spec.ts