sonar.projectKey=codeurjc-students_2025-GoEventsNow
sonar.organization=codeurjc-students

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/**/lcov.info

sonar.test.inclusions=**/*Test.java,**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/main.ts,**/test-setup.ts,**/environment*.ts
sonar.sourceEncoding=UTF-8