name: CD - Dev to Main

on:
    push:
        branches:
            - main
            - feature/**
    workflow_dispatch:

jobs:
    publish-dev:
        uses: ./.github/workflows/reusable-build-publish.yml
        with:
            image_tag: dev
        secrets: inherit