name: CD - Release

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            release_tag:
                description: 'Release tag to test'
                required: true
                default: '0.0.1'

jobs:
    publish-release:
        uses: ./.github/workflows/reusable-build-publish.yml
        with:
            image_tag: ${{ github.event.release.tag_name }}
            push_latest: true
        secrets: inherit